### ISSUE TITLE
Extension configured but not discovered on Jib runtime classpath

### ISSUE THREAD

**Issue by JWood48** [ryandens/javaagent-gradle-plugin#36] opened 2022-12-14 12:04 UTC
Followed the jib setup, but get this error when trying to build the jib image...

```
error running extension 'com.google.cloud.tools.jib.plugins.extension.NullExtension': extension configured but not discovered on Jib runtime classpath: com.ryandens.javaagent.JavaagentJibExtension
```

Using version 0.4.2, jib version 3.3.1 and gradle 7.6

What am I missing?

**Comment by ryandens** [comment] 2022-12-14 18:39
Hi @JWood48, I'm not sure. I have personally used this plugin with the exact versions you described. How are you registering the plugin in your build? The jib plugin looks for extension classes on the buildscript classpath. Here is how I configure the application built by the `gradle init` task to use the javaagent plugin with jib:

```kotlin
plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // following two plugins added by be to containerize the hello world app with a javaagent
    id("com.google.cloud.tools.jib") version "3.3.1"
    id("com.ryandens.javaagent-jib") version "0.4.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")
    // lower line added by me as an example javaagent to use 
    javaagent("io.opentelemetry.javaagent:opentelemetry-javaagent:1.21.0")
}

// this block added by me, for arm64 architectures like the M1 chip
jib.from.platforms {
    platform {
        architecture = "arm64"
        os = "linux"
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.9.1")
        }
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.ryandens.test.App")
}

```

Applying the `javaagent-jib` plugin does two things:
- Registers the task dependencies so that javaagents get resolved and copied to the appropriate directory before the image build 
- Configures the jib extension to run the javaagent jib plugin as its builds the image (done [here](https://github.com/ryandens/javaagent-gradle-plugin/blob/main/plugin/src/main/kotlin/com/ryandens/javaagent/JavaagentJibExtension.kt#L88)). 

Somehow, the javaagent jib extension is configured by the plugin, but the same class is not available on the buildscript classpath, which is unusual and is not a situation I can reproduce. If you can provide a minimal reproducer project and attach a Gradle build scan of the error, I'd be happy to take a look. 

If you have your buildscript classpath configured in a strange way, you could try explicitly adding the plugin to the buildscript classpath as recommended by jib [here](https://github.com/GoogleContainerTools/jib-extensions#using-jib-plugin-extensions-gradle). Still, I want to stress to other users that this should not be necessary and is likely a symptom of something else being wrong. 

This would look like:
```kotlin
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("com.ryandens:plugin:0.4.2")
        classpath("com.google.cloud.tools:jib-gradle-plugin:3.3.1")
    }
}
```

**Comment by JWood48** [comment] 2022-12-16 10:08
Tried adding the dependencies to the buildscript classpath, but same error... I also did a build scan and here is says that the plugin is loaded correctly for the project...

Unfortunately i'm not able to extract to a reproducible repo at the moment... Will try again at a later point in time...

**Comment by ryandens** [comment] 2022-12-16 22:09
If you link the build scan here, I can take a look. If not, I'll close this issue out until this issue can be more actionable.

**Comment by ryandens** [comment] 2022-12-23 21:32
Can't reproduce. If you can provide a way to reproduce it, please reopen the issue with the necessary information

**Closed by ryandens** 2022-12-23 21:32 UTC
Labels: bug

**Comment by JWood48** [comment] 2023-01-10 13:11
To follow up on this, I think i found the issue - it was fixed after including the plugins (jib and javaagent) in the right order both in the sub project and in the root project where they where defined with apply false

root project:
```
alias(libs.plugins.com.google.cloud.tools.jib) apply false
alias(libs.plugins.com.ryandens.javaagent.jib) apply false
```

sub project
```
alias(libs.plugins.com.google.cloud.tools.jib)
alias(libs.plugins.com.ryandens.javaagent.jib)
```

(plugins are defined in libs.versions.toml)
